### PR TITLE
Cleaned up for workshop

### PR DESCRIPTION
**Pull request by 5herlocked**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shapirov103 — COMMENTED** [review]
Why is rust dashboard deleted? I thought we could use it in the future to show how dev teams can create their own dashboards.

**Comment by 5herlocked** [comment]
application yml will be moved to the reference folder,

I can add the dashboards back in however the non OAM manifests were removed to reduce the confusion, though they can be moved to reference like a: "this is all that you have to do without OAM"

**Comment by shapirov103** [comment]
> application yml will be moved to the reference folder, and there's a reference manifest included in the WS instructions
> 
> I can add the dashboards back in however the non OAM manifests were removed to reduce the confusion, though they can be moved to reference like a: "this is all that you have to do without OAM"

Good on app.yml - sounds like a plan. 

Let's keep the dashboard in the reference folder.

**Review by shapirov103 — APPROVED** [review]
LGTM

**Pull request merged**
